spring:
  datasource:
    hikari:
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/board?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
      username: root
      password: youngwo1
      connection-test-query: SELECT 1
  thymeleaf:
    cache: false
  web:
    resources:
      cache:
        period: 0
  mail:
    host: smtp.gmail.com
    port: 587
    username: wooyastdy@gmail.com
    password: lvewqpahukhqahyg
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#spring.mail.host=smtp.gmail.com
#spring.mail.port=587
#spring.mail.username= ~~~@gmail.com // gmail 계정
#spring.mail.password=qcyuiqxjmjtgosqh // 앱 비밀번호
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.timeout=5000
#spring.mail.properties.mail.smtp.starttls.enable=true
# lvewqpahukhqahyg

       