spring:
  datasource:
    hikari:
      connection-test-query: SELECT 1

logging:
  config: classpath:logback-${spring.profiles.active}.xml

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    
